config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only:[:new, :create, :show]
  resource :session, only:[:new, :create, :destroy]
  resources :bands do
    resources :albums, only:[:new]
  end
  resources :albums, only:[:create,:edit,:show,:update,:destroy] do
    resources :tracks, only:[:new]
  end
  resources :tracks, only:[:create,:edit,:show,:update,:destroy]
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id          :integer          not null, primary key
#  band_id     :integer          not null
#  recorded_in :string           not null
#  title       :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Album < ApplicationRecord
  validates :band_id, presence: true, uniqueness: true
  validates :title, :recorded_in, presence: true

  belongs_to :band,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: :Band

  has_many :tracks,
    primary_key: :id,
    foreign_key: :album_id,
    dependent: :destroy,
    class_name: :Track
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :albums,
    primary_key: :id,
    foreign_key: :band_id,
    dependent: :destroy,
    class_name: :Album

  has_many :tracks,
    through: :albums,
    source: :tracks
end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id            :integer          not null, primary key
#  song          :string           not null
#  album_id      :integer          not null
#  lyrics        :text             not null
#  kind_of_track :string           not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Track < ApplicationRecord
  validates :album_id, presence: true, uniqueness: true
  validates :song, :lyrics, :kind_of_track, presence: true

  belongs_to :album,
    primary_key: :id,
    foreign_key: :album_id,
    class_name: :Album

  has_one :band,
    through: :album,
    source: :band
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(@password)
  end

  def reset_session_token
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return user if user && user.is_password?(password)
    nil
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end

  def require_logged_out
    redirect_to user_url if logged_in?
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_in_user!(user)
    session[:session_token] = user.session_token
  end

  def log_out!
    current_user.reset_session_token
    session[:session_token] = nil
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_logged_in

  def index
    @bands = Band.all
    render :index
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to bands_url
    else
      flash.now[:errors] = ["Couldnt create band for some reason"]
      redirect_to bands_url
    end
  end

  def new
    @band = Band.new
    render :new
  end

  def edit
    @band = selected_band
    render :edit
  end

  def show
    @band = selected_band
    render :show
  end

  def update
    @band = selected_band
    if @band.update_attributes(band_params)
      redirect_to bands_url
    else
      flash.now[:errors] = ["Failed to update band"]
      redirect_to edit_band_url
    end
  end

  def destroy
    @band = selected_band
    if @band
      @band.destroy
      redirect_to bands_url
    else
      flash.now[:errors] = ["Could not remove band"]
      redirect_to bands_url
    end
  end

  private

  def selected_band
    Band.find_by(id: params[:id])
  end

  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if user.nil?
      flash.now[:errors] = ["Incorrect username and/or password"]
      render :new
    else
      log_in_user!(user)
      redirect_to bands_url
    end
  end

  def destroy
    log_out!
    redirect_to new_session_url
  end

  def new
    render :new
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def show
    @user = selected_user

    if @user
      render :show
    else
      flash[:errors] = ["No such User"]
      redirect_to new_user_url
    end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid inputs for user"]
      redirect_to bands_url
    end
  end



  private

  def selected_user
    User.find_by(id: params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password_digest, :password)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bands/index.html.erb
<h1>Band List!</h1>

<%= link_to "Add new band", new_band_url %>

<% @bands.each do |band| %>
<ul>
  <li>
    <%= link_to "#{band.name}", band_url(band) %>
    <%= button_to "Band go bye bye", band_url(band), method: :delete %>
  </li>

</ul>
<% end %>

app/views/bands/new.html.erb
<h1>Add a new band!</h1>

<form action="<%= bands_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="text" name="band[name]">
  <input type="submit" name="Add Me!">
</form>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <% if current_user.nil? %>
    <%= link_to "Sign In Yo", new_session_url %>
    <%= link_to "Sign Up Yo", new_user_url %>
  <% else %>
    Hi <%= current_user.email  %>
    <%= button_to "Log Out :(", session_url, method: :delete%>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <ul>
    <% flash[:errors].each do |error| %>
      <li><%= error %></li>
      <% end %>
  </ul>
  <% end %>

app/views/users/new.html.erb
<h1>Sign Up Page!</h1>

<%= render "shared/errors" %>

<form action="<%= users_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="email">Email:</label>
  <input id="email" type="text" name="user[email]">
  <br>
  <label for="password">Password:</label>
  <input id="password" type="password" name="user[password]">
  <input type="submit" value="Come In">
</form>

app/views/users/show.html.erb
<h1>Hi <%= @user.email %></h1>